services:
  medicalequipmentmanagementsystem:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ConnectionStrings__DefaultConnection=Host=medicalequipment.db;Port=5432;Database=medicalequipmentdb;Username=postgres;Password=root
    ports:
      - "8081:5000"    # HTTP host:container
      - "8444:5001"    # HTTPS host:container
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - medicalequipment.db
    restart: unless-stopped
  
  medicalequipment.db:
    image: postgres:16
    environment:
      - POSTGRES_DB=medicalequipmentdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medicalequipmentdb"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped


